version: "3.6" 
services:
    web:
        build:
            context: front-end-petshop
            dockerfile: Dockerfile
        ports:
            - 2000:80
        networks:
            - petshop-network
        depends_on:
            - api
            - mongodb

    api:
        build:
            context: api-pet-shop
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - petshop-network
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        networks:
            - petshop-network
        ports:
            - "27022:27017"


networks:
    petshop-network:
        driver: bridge